### ISSUE TITLE
It couldn't launch the server with the nightly build of the WP-CLI

### ISSUE THREAD

**Issue by velthgithub** [miya0001/wp-instant-setup#3]
3月中旬より、新規で環境を作ると下記のエラーにより環境が立ち上がりません。

```
Warning: Unknown: failed to open stream: phar error: invalid url or non-existent phar "phar:各環境/bin/wp/vendor/wp-cli/server-command/router.php" in Unknown on line 0

Fatal error: Unknown: Failed opening required 'phar:各環境/bin/wp/vendor/wp-cli/server-command/router.php' (include_path='.:') in Unknown on line 0
```
http://wp-cli.org/#installing
を参照すると、
インストールするpharが
```
if ! bin/wp --info ; then
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
    rm -fr bin && mkdir bin
    mv wp-cli-nightly.phar bin/wp
    chmod 755 bin/wp
fi
```

wp-cli-nightlyがwp-cliになるかと思われます。

**Comment by velthgithub** [comment]
修正したので、pullリクを送りました！

**Comment by miya0001** [comment]
ありがとうございます。

このプロジェクトではナイトリービルドという俗にいうベータ版的な扱いのWP-CLIを意図的に使っています。
これは正規版が出る前にWP-CLIが潜在的に持つ不具合をみつけるためです。

https://make.wordpress.org/cli/handbook/installing/#alternative-installation-methods

今回の不具合もナイトリービルドに新規に仕込まれた不具合の気がします。
WP-CLI本体の方でなんらかのフィックスが必要だと思われるので調べます。

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/server-command/issues/13

**Comment by miya0001** [comment]
上のリンク先にあるとおりWP-CLI側の不具合ということで原因を調べ中です。
WP-CLI側の修正内容をみてこのプロジェクト側で何らかの修正が必要であれば修正します。
ちょっとまご不便をおかけするかもですが、適当にフォークして対処願います。m(_ _)m

**Comment by velthgithub** [comment]
ナイトリービルドの意味合いはそこにあったんですね。
時系列的にも、[wp-cli/wp-cli@436fc0a](https://github.com/wp-cli/wp-cli/pull/3923/commits/436fc0ac509cbf87b497e5893a3aab44f4c473d0)
のコミットあたりから起きていました。

ご対応ありがとうございます！！！

**Comment by miya0001** [comment]
WP-CLIのほうで不具合が修正されましたのでクローズしますね。
